exp := lit;
lit := str | num |char | nil | bool | kw;

str := #"\"[^\"]*\"";

num := long | double | ratio | bign | bigdec | octal | hex | radix;
long := #"-?[0-9]+[lL]?";
double := #"-?[0-9]*\.[0-9]+([eE]-?[0-9]+)?"
        | #"-?Infinity"
        | #"-?NaN";
ratio := #"-?[0-9]+/-?[0-9]+";
bign := #"-?[0-9]+[nN]";
bigdec := #"-?[0-9]*\.[0-9]+([eE]-?[0-9]+)?M"
octal := #"-?0[0-7]+"
hex := #"-?0x[0-9a-fA-F]+"
radix := #"-?([2-9]|[12][0-9]|3[0-6])r[0-9a-zA-z]+"

char := #"\\." | char_uni | char_oct | char_named;
char_uni := #"\\u[0-9a-fA-F]{4}"
char_oct := #"\\o[0-7]{3,4}"
char_named := '\\newline' | '\\return' | '\\space' | '\\tab' | '\\formfeed' | '\\backspace';

nil := 'nil'

bool := 'true' | 'false'

kw := #":[^\d\^`\\\"#~@:()\[\]{}\s,][^\^`\\\"#~@()\[\]{}\s,]*"